name: core
channels:
  - defaults
  - pytorch
dependencies:
  - pip=20.1.1
  - python=3.7.6
  - pytorch=1.10
  - torchvision=0.11.0
  - cudatoolkit=11.3
  - tensorflow=2.2.0
  - tensorboard=2.6.0
  - absl-py=0.13.0
  - pyparsing=2.4.7
  - pillow=6.1.0
  - h5py=2.10.0
  - pyyaml=5.4.1
  - moviepy=1.0.1
  - numpy=1.20
  - conda-forge::matplotlib=3.2.2
  - conda-forge::gym=0.19.0
  - conda-forge::ffmpeg=4.4.0
  - conda-forge::libiconv=1.16
  - conda-forge::imageio=2.6.1
  - pip:
    - termcolor==1.1.0
    - dm_control
    - git+ssh://git@github.com/sebimarkgraf/occluded_dmc.git
    - imageio-ffmpeg
    - wandb
